# staging pypi
pkg_domain := "release-staging"
pkg_repo := "stagec7n"
pkg_region := "us-east-1"


pkg-login:
  #!/usr/bin/env bash
  set -euxo pipefail

  export AWS_DEFAULT_REGION={{pkg_region}}

  export CODEARTIFACT_OWNER=`aws sts get-caller-identity --query Account --output text`
  export CODEARTIFACT_REPOSITORY_URL=`aws codeartifact get-repository-endpoint --domain {{pkg_domain}} --domain-owner $CODEARTIFACT_OWNER --repository {{pkg_repo}} --format pypi --query repositoryEndpoint --output text`
  export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain {{pkg_domain}} --domain-owner $CODEARTIFACT_OWNER --query authorizationToken --output text`
  export CODEARTIFACT_USER=aws

  poetry config repositories.{{pkg_repo}} $CODEARTIFACT_REPOSITORY_URL
  poetry config http-basic.{{pkg_repo}} $CODEARTIFACT_USER $CODEARTIFACT_AUTH_TOKEN

  # Note: `aws codeartifact login --tool pip` updates user-level pip settings. As a finer-grained alternative, we can
  # build a PyPI index URL and use it only inside our virtual environment.
  export PYPI_INDEX_URL="https://${CODEARTIFACT_USER}:${CODEARTIFACT_AUTH_TOKEN}@${CODEARTIFACT_REPOSITORY_URL#*//}simple/"
  python3 -m pip config --site set global.index-url "$PYPI_INDEX_URL"
